// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package chat_server

import (
	"time"
)

type Message struct {
	ID        string    `json:"id"`
	User      string    `json:"user"`
	CreatedAt time.Time `json:"createdAt"`
	Text      string    `json:"text"`
}

type RAMUsage struct {
	Total       int     `json:"total"`
	Used        int     `json:"used"`
	UsedPercent float64 `json:"usedPercent"`
}

type ServerUsage struct {
	CPU []float64 `json:"cpu"`
	RAM *RAMUsage `json:"ram"`
}
